include:

  - board: nrf52840dk_nrf52840
    shield: settings_reset
  - board: sofle_left
    shield: nice_view_adapter nice_view
    artifact-name: sofle_left_nice_view
    snippet: studio-rpc-usb-uart
  - board: sofle_right
    shield: nice_view_adapter nice_view_custom
    artifact-name: sofle_right_nice_view
